---
title: "ubp todos"
description: |
  TODOs for UBP.
author:
  - name: jg
    #url: https://example.com/norajones
date: 12-09-2020
output:
  distill::distill_article:
    self_contained: false
---
```{r, eval = FALSE, echo = FALSE, results='hide'}
library(distill)
create_website("esbh", "ESBH Site")

distill::create_blog(dir = "2020-12-09_ubp_todos", title = "ubp todos")

usethis::use_git() 

create_post(
  title = "ubp todos", # mandatory
  author = "auto",
  slug = "auto", # generates a website slug (URL)
  date_prefix = TRUE, # adds date for sorting
  draft = TRUE, 
  edit = interactive()
)
# git remote rm origin
usethis::use_github() # this works if you have already configured a GitHub Personal Access Token

#  Failed to push and set tracking branch.
#   This often indicates a problem with git2r and the credentials.
#   Try this in the shell, to complete the set up:
# git push --set-upstream origin master
```



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.


